### ISSUE TITLE
Malicious code (redundant and intentional)

### ISSUE THREAD

**Issue by kalatitude** [webworker01/freshubuntu#1]
Why does a screen styling script need to get my ip address every 600 (10min)? It's literally the first function in the script. Cool story bro. I found several other issues in your bullshit little script too. I'll be posting those as well. Then I'll be visiting your drive for a little 1 on 1, bitch

**Comment by webworker01** [comment]
IP address is retrieved to display on your screen, and they can change. Luckily, the code you picked out is open source and can be edited.

I welcome any thoughtful improvements to the code I give out for free. 

Calling anything I do malicious and then physically threatening me is some psycho level stuff.
